name: strTwinsCI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
  
    - name: Setup radare
      run: git clone https://github.com/radareorg/radare2.git && radare2/sys/install.sh
      
    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
